stop-words = "../topic_modeling/lemur-stopwords.txt"
prefix = "../topic_modeling/"
dataset = "data"
corpus = "line.toml"
index = "people-idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"